version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root0000
      MYSQL_DATABASE: TestDB
    command:
     - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./.db/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    