export const FETCH_BARCHART_DATA = 'FETCH_BARCHART_DATA';
export const FETCH_BARCHART_DATA_SUCCESS = 'FETCH_BARCHART_DATA_SUCCESS';
export const FETCH_BARCHART_DATA_FAIL = 'FETCH_BARCHART_DATA_FAIL';

export const FETCH_LINECHART_DATA = 'FETCH_LINECHART_DATA';
export const FETCH_LINECHART_DATA_SUCCESS = 'FETCH_LINECHART_DATA_SUCCESS';
export const FETCH_LINECHART_DATA_FAIL = 'FETCH_LINECHART_DATA_FAIL';
